version: "3.7"

services:
  webapp:
    build:
      context: ./
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
